### ISSUE TITLE
./gradlew eclipse doesn't work

### ISSUE THREAD

**Issue by ghost** [fge/java7-fs-dropbox#1]
When perform ./gradlew eclipse in java7-fs-dropbox, it throws an exception:

![capture](https://cloud.githubusercontent.com/assets/3638320/5364612/c36c7eee-8006-11e4-87cb-feda13953160.PNG)

**Comment by fge** [comment]
Can you paste the content as text, please?

**Comment by ghost** [comment]
- What went wrong:
  Execution failed for task ':eclipseClasspath'.
  
  > Could not resolve all dependencies for configuration ':compile'.
  > Could not find com.github.fge:java7-fs-base:0.0.1-SNAPSHOT.
  >  Required by:
  >      com.github.fge:java7-fs-dropbox-master:0.0.1-SNAPSHOT
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 10.41 secs

**Comment by fge** [comment]
Closing... It works after all (seen on SO chatroom)
